name: Build and push Docker compo-decompo image
on:
  push:
    paths:
      - 'src/autocompose.py'
      - 'docker/autocompose/**'
      - 'docker/decomposerize/**'
      - 'docker/compo-decompo/**'
      - '.github/workflows/docker-compo-decompo.yml'
      - '.github/workflows/docker-build-template.yml'
  workflow_dispatch:
    inputs:
      amd64:
        description: 'Enable linux/amd64 build'
        type: boolean
        default: true
      armhf:
        description: 'Enable linux/armhf build'
        type: boolean
        default: false
      arm64:
        description: 'Enable linux/arm64 build'
        type: boolean
        default: false

jobs:
  init:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     platform: [linux/amd64, linux/armhf, linux/arm64]
    outputs:
      cache_key: ${{ steps.cachekey.outputs.CACHE_KEY }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout decomposerize (fork)
        id: checkout-decompo
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/decomposerize
          path: decomposerize
          fetch-depth: 0

      - name: Set cache key
        id: cachekey
        run: echo "CACHE_KEY=${{ runner.os }}-buildx-${{ hashFiles('decomposerize/yarn.lock', 'poetry.lock') }}" >> $GITHUB_OUTPUT

  build-and-push:
    needs: init
    uses: ./.github/workflows/docker-build-template.yml
    with:
      checkout: false
      amd64: ${{ inputs.amd64 }}
      armhf: ${{ inputs.armhf }}
      arm64: ${{ inputs.arm64 }}
      image_name: docker-compo-decompo
      dockerfile: ./docker/compo-decompo/Dockerfile
      build_args: POETRY_VERSION=1.8.5
      cache_key: ${{ needs.init.outputs.cache_key }}
